name: Android CI

on:
  push:
    branches: [ main ]  # Запускается при пуше в main
  pull_request:
    branches: [ main ]  # Или при создании Pull Request

jobs:
  build:

    runs-on: ubuntu-latest  # Сервер, где будет запускаться сборка

    steps:
      - name: load code
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17  # Версия Java, подходящая для Android

      - name: create project
        run: ./gradlew assembleDebug

      - name: run tests
        run: ./gradlew testDebugUnitTest
